-- autocmd は VeryLazy イベント時に自動的に読み込まれる
-- LazyVim のデフォルト autocmd: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- 追加の autocmd は `vim.api.nvim_create_autocmd` を使って定義する
--
-- デフォルト autocmd を削除する場合はグループ名を指定する (LazyVim のデフォルトは "lazyvim_" プレフィックス)
-- 例: vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
